### ISSUE TITLE
Cannot Get Serving Default Signature

### ISSUE THREAD

**Issue by alexdriedger** [tensorflow/java#75]
`SignatureDef sig = model.metaGraphDef().getSignatureDefMap().get("serving_default");` does not compile (it did a week ago).

It has the error `Error: java: cannot access com.google.protobuf.MessageOrBuilder
  class file for com.google.protobuf.MessageOrBuilder not found`

This error showed up in the past week using the TF 2.0 (`0.1.0-SNAPSHOT`)

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: no
- TensorFlow installed from (source or binary): maven
- TensorFlow version (use command below): 2.x June 21 Snapshot
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**
Does not compile

**Describe the expected behavior**
Compiles

**Code to reproduce the issue**
```java
SavedModelBundle model = SavedModelBundle.load(pathToBundle, "serve");
SignatureDef sig = model.metaGraphDef().getSignatureDefMap().get("serving_default");
```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

I'm using this code to get the input and output names of my model. See [this Stack Overflow answer](https://stackoverflow.com/a/61232138/7219360) and [this Stack Overflow answer](https://stackoverflow.com/a/62295153/7219360)

**Comment by karllessard** [comment]
Hi @alexdriedger , 

I think this is related to [this issue](https://github.com/tensorflow/java-models/issues/4) which has been resolved now. Can you please try it again and let us know?

**Comment by alexdriedger** [comment]
Adding the missing dependencies solves my problem

```
        <dependency>
            <groupId>org.tensorflow</groupId>
            <artifactId>tensorflow-tools</artifactId>
            <version>0.1.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>com.google.protobuf</groupId>
            <artifactId>protobuf-java</artifactId>
            <version>3.12.2</version>
        </dependency>
```

But it still fails when I remove the dependencies

**Comment by karllessard** [comment]
Remove these dependencies (they should be transitively added by `tensorflow-core-platform` or `tensorflow-core-api`, depending on what you are using) and make sure to refresh your snapshots (`mvn install -U`). 

To double check, you can view the pom file of the `tensorflow-core-api` artifact in your local maven repository, if it is almost empty then it means that you are still using the old files and should probably delete that whole directory manually.

**Comment by karllessard** [comment]
Hi @alexdriedger , do you still have issues to build and retrieve transitive dependencies? Do you have any update to share?

**Comment by karllessard** [comment]
Closing this old ticket, accessing model default signature can now be done very easily by calling
`savedModel.function(Signature.DEFAULT_KEY)`. You can even invoke this signature directly with `savedModel.call(inputTensorsMap)`.
